FROM python
# can you find a lighter image?

WORKDIR /app

# copy the requirements file in the workdir
RUN

# install the Python requirements
RUN

# copy the app files and directories
RUN

# start booking.py when the container is started
CMD 
